apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: devsu-demo
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*,localhost,127.0.0.1,demo.local"
  DATABASE_NAME: "db.sqlite3"
